verticalLayout(
  fluidRow(
    column(6,
           uiOutput('aggByCtrl')
    ),
    column(6,
           uiOutput('aggTargetCtrl')
    )
  ),
  fluidRow(
    column(6, 
           uiOutput('aggMethCtrl')
    )
  ),
  fluidRow(
    column(6,
           uiOutput('shareOfCtrl')
    ),
    column(6,
           uiOutput('shareTargetCtrl')
    ) 
  )        
)